This notebook gives a short introduction on some concepts of the NumPy library.

Numpy is a library that contains functions for fast mathematical computation with Python. For the speed-up, it relies on C-language bindings. Its concept is similar to Matlab, i.e. working mainly with arrays and matrices.

Note that this is not a "complete" Numpy tutorial, but only introduces the concepts which are important for our lecture.

## Array Creation

The fundamental working horse of NumPy is the multidimensional array object, which allows fast computation on all sorts of operations. There are different ways to create this object:

In [1]:
import numpy as np

In [3]:
np.array([2, 3, 4]) # create numpy array from a Python list (1 dimension)

array([2, 3, 4])

In [6]:
np.array( [[1, 2], [3, 4] ]) # create numpy array from a Python list (2 dimensions)

array([[1, 2],
       [3, 4]])

In [8]:
np.zeros((3, 4)) # create numpy array with all zeros, 2-dimension, shape 3x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((2, 3, 4)) # same, but for 3-dimensions

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.random.randn(3, 4) # create numpy array with random values, 2-dimension, shape 3x4

array([[ 0.05951884,  1.40468203,  0.52545036,  0.86723891],
       [-2.77982427, -1.09323925, -0.26671464, -0.6693658 ],
       [-1.28116678,  0.14738947, -0.07596963,  0.90264507]])

## Array Operations

In [72]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
a.dot(b)  # Dot product of two arrays, inner-product if both are 1-D arrays

20

In [73]:
a = np.array([[1, -2, 3], [2, 2, 2]]) # 2D-array, shape 2x3
a

array([[ 1, -2,  3],
       [ 2,  2,  2]])

In [74]:
b = np.array([[2, 3, 4, 1], [1, 1, 1, 0], [2, 2, 2, 1]]) # 2D-array, shape 3x4
b

array([[2, 3, 4, 1],
       [1, 1, 1, 0],
       [2, 2, 2, 1]])

In [75]:
c = a.dot(b) # when multiplying two 2-D arrays, this is now a matrix multiplication
c

array([[ 6,  7,  8,  4],
       [10, 12, 14,  4]])

We can also perform piece-wise operations on arrays that are applied to every element of the array:

In [78]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a + b)
print(a - b)

[3 5 7]
[-1 -1 -1]


In [67]:
np.maximum(c, 0) # take the maximum between zero and each element of the array

array([[ 0,  7,  8,  4],
       [ 0, 12, 14,  4]])

In [68]:
np.square(c)  # take the square of each element of the array

array([[100,  49,  64,  16],
       [ 36, 144, 196,  16]])

Other operations that are of importance:

In [80]:
c

array([[ 6,  7,  8,  4],
       [10, 12, 14,  4]])

In [79]:
c.sum() # sum-up all of the elements in the array

65

In [82]:
c.T # transpose elements of the array

array([[ 6, 10],
       [ 7, 12],
       [ 8, 14],
       [ 4,  4]])